---
version: "3.9"
services:
  dev_container:
    hostname: omada-api-dev
    build:
      context: .
      dockerfile: ./Dockerfile.dev
      args:
        - AWS_PIP_INDEX_URL
        - BUILD_PYTHON_VERSION
    environment:
      XDG_DATA_HOME: /app/tmp/xdg/data
      XDG_CONFIG_HOME: /app/tmp/xdg/config
      XDG_STATE_HOME: /app/tmp/xdg/state
      XDG_CACHE_HOME: /app/tmp/xdg/cache
    volumes:
      - .:/app
      - ~/.aws:/root/.aws
      - ~/.gitconfig:/root/.gitconfig
      - ~/.ssh:/root/.ssh
