name: Release
on:
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip poetry
      - name: Build packages
        run: poetry build
      - name: Publish distribution to Test PyPI
        run: |
          poetry config pypi-token.test-pypi "${{ secrets.TEST_PYPI_API_TOKEN }}"
          poetry publish -r test-pypi
      # - name: Publish distribution to PRODUCTION PyPI
      #   uses: pypa/gh-action-pypi-publish@master
      #   with:
      #     password: ${{ secrets.PYPI_API_TOKEN }}
